version: "3"

tasks:
  run:
    desc: "Executa o binário da aplicação"
    cmd: bazelisk run //apps/js-legacy-api-items:main
  build:
    desc: "Compila o binário da aplicação"
    cmd: bazelisk build //apps/js-legacy-api-items:main
  test:
    desc: "Executa os testes da aplicação"
    cmd: bazelisk test //apps/js-legacy-api-items:test --test_output=all --test_arg=--coverage
  image:
    desc: "Constrói uma imagem docker da aplicação localmente"
    cmd: bazelisk run //apps/js-legacy-api-items:image
