version: "3"

tasks:
  run:
    desc: "Executa o binário da aplicação"
    cmd: bazel run //apps/js-legacy-api-items:main
  build:
    desc: "Compila o binário da aplicação"
    cmd: bazel build //apps/js-legacy-api-items:main
  test:
    desc: "Executa os testes da aplicação"
    cmd: bazel test //apps/js-legacy-api-items:test --test_output=all --test_arg=--coverage
